name: 3. Auto Fork (Interactive)

on:
  workflow_dispatch: 
    inputs:
      target:
        description: 'Target Repo (contoh: owner/repo)'
        required: true
      quantity:
        description: 'Jumlah eksekusi'
        required: true
      duration:
        description: 'Durasi pengerjaan dalam jam'
        required: true
      start_index:
        description: 'Mulai dari token urutan ke berapa (Mulai dari 1)'
        required: true
        default: '1'
      lang:
        description: 'Bahasa output (id/en)'
        required: false
        default: 'id'
      engine_name:
        description: 'Nama Mesin (contoh: Engine 4)'
        required: false
        default: 'Engine 4'
      buyer_id:
        description: 'Telegram ID Pembeli untuk Notifikasi Live'
        required: false
        default: ''

jobs:
  execute-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Packages
        run: pip install requests

      - name: 🚀 RUN FORK SQUAD
        env:
          WORKER_TOKENS: ${{ secrets.WORKER_TOKENS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_GROUP_ID: ${{ secrets.TELEGRAM_GROUP_ID }}
          ACTION_TYPE: "FORKS"
          TARGET_REPOS: ${{ github.event.inputs.target }}
          INPUT_QTY: ${{ github.event.inputs.quantity }}
          INPUT_DUR: ${{ github.event.inputs.duration }}
          INPUT_START: ${{ github.event.inputs.start_index }}
          INPUT_LANG: ${{ github.event.inputs.lang }}
          INPUT_ENGINE_NAME: ${{ github.event.inputs.engine_name }}
          BUYER_ID: ${{ github.event.inputs.buyer_id }}
        run: python -u auto.py
