name: Auto Star Squad (Interactive)

on:
  workflow_dispatch: 
    inputs:
      target:
        description: 'Target Repository (owner/repo)'
        required: true
      quantity:
        description: 'Jumlah eksekusi'
        required: true
      duration:
        description: 'Durasi pengerjaan dalam jam'
        required: true
      start_index:
        description: 'Mulai dari token urutan ke berapa'
        required: true

jobs:
  execute-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Packages
        run: pip install requests

      - name: 🚀 RUN STAR SQUAD
        env:
          WORKER_TOKENS: ${{ secrets.WORKER_TOKENS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          ACTION_TYPE: "STARS"
          TARGET_REPOS: ${{ github.event.inputs.target }}
          INPUT_QTY: ${{ github.event.inputs.quantity }}
          INPUT_DUR: ${{ github.event.inputs.duration }}
          INPUT_START: ${{ github.event.inputs.start_index }}
        run: python -u auto.py
